<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        spacing: 10
        padding: 50
        Button:
            text: "Hello World!"
        Button:
            text: "Goodbye World!"
        Button:
            text: "Good Morning"
            pos_hint: {'center_x':.5}
            size_hint: (None, None)
            width: 200
            height: 50
